[server]
headless = true
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#E85D42"
backgroundColor = "#FFF9ED"
secondaryBackgroundColor = "#FFEFDE"
textColor = "#351C1C"
linkColor = "#D94683"
linkUnderline = false
borderColor = "#EDDAD0"
baseRadius = "full"
buttonRadius = "full"
showWidgetBorder = true
baseFontSize = 16
font = "sans-serif"
headingFont = "serif"
chartCategoricalColors = ["#FF6A3D", "#FF4F9A", "#F780BC", "#F4B98E", "#D193C2", "#FF9173"]
chartSequentialColors = ["#FFF3E4", "#FFCBB6", "#FF9173", "#FF6A3D", "#D94683"]

[theme.sidebar]
primaryColor = "#E85D42"
backgroundColor = "#FFEFDE"
secondaryBackgroundColor = "#FFF9ED"
textColor = "#351C1C"
borderColor = "#EDDAD0"
baseRadius = "full"
buttonRadius = "full"
showWidgetBorder = true
